// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: booking/service.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_booking_service_proto protoreflect.FileDescriptor

const file_booking_service_proto_rawDesc = "" +
	"\n" +
	"\x15booking/service.proto\x12\abooking\x1a\x16booking/messages.proto2\x84\x05\n" +
	"\x0eBookingService\x12@\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x10.booking.Booking\x12:\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x10.booking.Booking\x12K\n" +
	"\fListBookings\x12\x1c.booking.ListBookingsRequest\x1a\x1d.booking.ListBookingsResponse\x12B\n" +
	"\x0eConfirmBooking\x12\x1e.booking.ConfirmBookingRequest\x1a\x10.booking.Booking\x12@\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x10.booking.Booking\x12:\n" +
	"\n" +
	"MarkSeated\x12\x1a.booking.MarkSeatedRequest\x1a\x10.booking.Booking\x12>\n" +
	"\fMarkFinished\x12\x1c.booking.MarkFinishedRequest\x1a\x10.booking.Booking\x12:\n" +
	"\n" +
	"MarkNoShow\x12\x1a.booking.MarkNoShowRequest\x1a\x10.booking.Booking\x12i\n" +
	"\x16CheckTableAvailability\x12&.booking.CheckTableAvailabilityRequest\x1a'.booking.CheckTableAvailabilityResponseB:Z8github.com/bookingcontrol/booker-contracts-go/v1/bookingb\x06proto3"

var file_booking_service_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),           // 0: booking.CreateBookingRequest
	(*GetBookingRequest)(nil),              // 1: booking.GetBookingRequest
	(*ListBookingsRequest)(nil),            // 2: booking.ListBookingsRequest
	(*ConfirmBookingRequest)(nil),          // 3: booking.ConfirmBookingRequest
	(*CancelBookingRequest)(nil),           // 4: booking.CancelBookingRequest
	(*MarkSeatedRequest)(nil),              // 5: booking.MarkSeatedRequest
	(*MarkFinishedRequest)(nil),            // 6: booking.MarkFinishedRequest
	(*MarkNoShowRequest)(nil),              // 7: booking.MarkNoShowRequest
	(*CheckTableAvailabilityRequest)(nil),  // 8: booking.CheckTableAvailabilityRequest
	(*Booking)(nil),                        // 9: booking.Booking
	(*ListBookingsResponse)(nil),           // 10: booking.ListBookingsResponse
	(*CheckTableAvailabilityResponse)(nil), // 11: booking.CheckTableAvailabilityResponse
}
var file_booking_service_proto_depIdxs = []int32{
	0,  // 0: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	1,  // 1: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	2,  // 2: booking.BookingService.ListBookings:input_type -> booking.ListBookingsRequest
	3,  // 3: booking.BookingService.ConfirmBooking:input_type -> booking.ConfirmBookingRequest
	4,  // 4: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	5,  // 5: booking.BookingService.MarkSeated:input_type -> booking.MarkSeatedRequest
	6,  // 6: booking.BookingService.MarkFinished:input_type -> booking.MarkFinishedRequest
	7,  // 7: booking.BookingService.MarkNoShow:input_type -> booking.MarkNoShowRequest
	8,  // 8: booking.BookingService.CheckTableAvailability:input_type -> booking.CheckTableAvailabilityRequest
	9,  // 9: booking.BookingService.CreateBooking:output_type -> booking.Booking
	9,  // 10: booking.BookingService.GetBooking:output_type -> booking.Booking
	10, // 11: booking.BookingService.ListBookings:output_type -> booking.ListBookingsResponse
	9,  // 12: booking.BookingService.ConfirmBooking:output_type -> booking.Booking
	9,  // 13: booking.BookingService.CancelBooking:output_type -> booking.Booking
	9,  // 14: booking.BookingService.MarkSeated:output_type -> booking.Booking
	9,  // 15: booking.BookingService.MarkFinished:output_type -> booking.Booking
	9,  // 16: booking.BookingService.MarkNoShow:output_type -> booking.Booking
	11, // 17: booking.BookingService.CheckTableAvailability:output_type -> booking.CheckTableAvailabilityResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_booking_service_proto_init() }
func file_booking_service_proto_init() {
	if File_booking_service_proto != nil {
		return
	}
	file_booking_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_service_proto_rawDesc), len(file_booking_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_service_proto_goTypes,
		DependencyIndexes: file_booking_service_proto_depIdxs,
	}.Build()
	File_booking_service_proto = out.File
	file_booking_service_proto_goTypes = nil
	file_booking_service_proto_depIdxs = nil
}
