// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: venue/availability_messages.proto

package venue

import (
	common "github.com/bookingcontrol/booker-contracts-go/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на проверку доступности
type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Slot          *common.Slot           `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	PartySize     int32                  `protobuf:"varint,3,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_venue_availability_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_availability_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_venue_availability_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAvailabilityRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetSlot() *common.Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *CheckAvailabilityRequest) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

// Ответ с информацией о доступности
type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableAvailability   `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_venue_availability_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_availability_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_venue_availability_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAvailabilityResponse) GetTables() []*TableAvailability {
	if x != nil {
		return x.Tables
	}
	return nil
}

type TableAvailability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Table           *common.TableRef       `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Available       bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	MergedWithTable *common.TableRef       `protobuf:"bytes,4,opt,name=merged_with_table,json=mergedWithTable,proto3" json:"merged_with_table,omitempty"` // If this table can be merged with another table
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TableAvailability) Reset() {
	*x = TableAvailability{}
	mi := &file_venue_availability_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAvailability) ProtoMessage() {}

func (x *TableAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_venue_availability_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAvailability.ProtoReflect.Descriptor instead.
func (*TableAvailability) Descriptor() ([]byte, []int) {
	return file_venue_availability_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TableAvailability) GetTable() *common.TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *TableAvailability) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *TableAvailability) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TableAvailability) GetMergedWithTable() *common.TableRef {
	if x != nil {
		return x.MergedWithTable
	}
	return nil
}

var File_venue_availability_messages_proto protoreflect.FileDescriptor

const file_venue_availability_messages_proto_rawDesc = "" +
	"\n" +
	"!venue/availability_messages.proto\x12\x05venue\x1a\x13common/events.proto\"v\n" +
	"\x18CheckAvailabilityRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12 \n" +
	"\x04slot\x18\x02 \x01(\v2\f.common.SlotR\x04slot\x12\x1d\n" +
	"\n" +
	"party_size\x18\x03 \x01(\x05R\tpartySize\"M\n" +
	"\x19CheckAvailabilityResponse\x120\n" +
	"\x06tables\x18\x01 \x03(\v2\x18.venue.TableAvailabilityR\x06tables\"\xaf\x01\n" +
	"\x11TableAvailability\x12&\n" +
	"\x05table\x18\x01 \x01(\v2\x10.common.TableRefR\x05table\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12<\n" +
	"\x11merged_with_table\x18\x04 \x01(\v2\x10.common.TableRefR\x0fmergedWithTableB8Z6github.com/bookingcontrol/booker-contracts-go/v1/venueb\x06proto3"

var (
	file_venue_availability_messages_proto_rawDescOnce sync.Once
	file_venue_availability_messages_proto_rawDescData []byte
)

func file_venue_availability_messages_proto_rawDescGZIP() []byte {
	file_venue_availability_messages_proto_rawDescOnce.Do(func() {
		file_venue_availability_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_venue_availability_messages_proto_rawDesc), len(file_venue_availability_messages_proto_rawDesc)))
	})
	return file_venue_availability_messages_proto_rawDescData
}

var file_venue_availability_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_venue_availability_messages_proto_goTypes = []any{
	(*CheckAvailabilityRequest)(nil),  // 0: venue.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil), // 1: venue.CheckAvailabilityResponse
	(*TableAvailability)(nil),         // 2: venue.TableAvailability
	(*common.Slot)(nil),               // 3: common.Slot
	(*common.TableRef)(nil),           // 4: common.TableRef
}
var file_venue_availability_messages_proto_depIdxs = []int32{
	3, // 0: venue.CheckAvailabilityRequest.slot:type_name -> common.Slot
	2, // 1: venue.CheckAvailabilityResponse.tables:type_name -> venue.TableAvailability
	4, // 2: venue.TableAvailability.table:type_name -> common.TableRef
	4, // 3: venue.TableAvailability.merged_with_table:type_name -> common.TableRef
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_venue_availability_messages_proto_init() }
func file_venue_availability_messages_proto_init() {
	if File_venue_availability_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_venue_availability_messages_proto_rawDesc), len(file_venue_availability_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_venue_availability_messages_proto_goTypes,
		DependencyIndexes: file_venue_availability_messages_proto_depIdxs,
		MessageInfos:      file_venue_availability_messages_proto_msgTypes,
	}.Build()
	File_venue_availability_messages_proto = out.File
	file_venue_availability_messages_proto_goTypes = nil
	file_venue_availability_messages_proto_depIdxs = nil
}
