// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: venue/schedule_messages.proto

package venue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Расписание работы заведения
type OpeningHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Days          []*DayHours            `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeningHours) Reset() {
	*x = OpeningHours{}
	mi := &file_venue_schedule_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeningHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningHours) ProtoMessage() {}

func (x *OpeningHours) ProtoReflect() protoreflect.Message {
	mi := &file_venue_schedule_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningHours.ProtoReflect.Descriptor instead.
func (*OpeningHours) Descriptor() ([]byte, []int) {
	return file_venue_schedule_messages_proto_rawDescGZIP(), []int{0}
}

func (x *OpeningHours) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *OpeningHours) GetDays() []*DayHours {
	if x != nil {
		return x.Days
	}
	return nil
}

type DayHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weekday       int32                  `protobuf:"varint,1,opt,name=weekday,proto3" json:"weekday,omitempty"`                     // 0-6, 0=Sunday
	OpenTime      string                 `protobuf:"bytes,2,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`    // HH:MM
	CloseTime     string                 `protobuf:"bytes,3,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"` // HH:MM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayHours) Reset() {
	*x = DayHours{}
	mi := &file_venue_schedule_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayHours) ProtoMessage() {}

func (x *DayHours) ProtoReflect() protoreflect.Message {
	mi := &file_venue_schedule_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayHours.ProtoReflect.Descriptor instead.
func (*DayHours) Descriptor() ([]byte, []int) {
	return file_venue_schedule_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DayHours) GetWeekday() int32 {
	if x != nil {
		return x.Weekday
	}
	return 0
}

func (x *DayHours) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *DayHours) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

// Специальные часы работы
type SpecialHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	OpenTime      string                 `protobuf:"bytes,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string                 `protobuf:"bytes,4,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	IsClosed      bool                   `protobuf:"varint,5,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialHours) Reset() {
	*x = SpecialHours{}
	mi := &file_venue_schedule_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialHours) ProtoMessage() {}

func (x *SpecialHours) ProtoReflect() protoreflect.Message {
	mi := &file_venue_schedule_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialHours.ProtoReflect.Descriptor instead.
func (*SpecialHours) Descriptor() ([]byte, []int) {
	return file_venue_schedule_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SpecialHours) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *SpecialHours) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SpecialHours) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *SpecialHours) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

func (x *SpecialHours) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

// Запросы для работы с расписанием
type SetOpeningHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Days          []*DayHours            `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOpeningHoursRequest) Reset() {
	*x = SetOpeningHoursRequest{}
	mi := &file_venue_schedule_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOpeningHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOpeningHoursRequest) ProtoMessage() {}

func (x *SetOpeningHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_schedule_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOpeningHoursRequest.ProtoReflect.Descriptor instead.
func (*SetOpeningHoursRequest) Descriptor() ([]byte, []int) {
	return file_venue_schedule_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SetOpeningHoursRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *SetOpeningHoursRequest) GetDays() []*DayHours {
	if x != nil {
		return x.Days
	}
	return nil
}

type GetOpeningHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpeningHoursRequest) Reset() {
	*x = GetOpeningHoursRequest{}
	mi := &file_venue_schedule_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpeningHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpeningHoursRequest) ProtoMessage() {}

func (x *GetOpeningHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_schedule_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpeningHoursRequest.ProtoReflect.Descriptor instead.
func (*GetOpeningHoursRequest) Descriptor() ([]byte, []int) {
	return file_venue_schedule_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetOpeningHoursRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

type SetSpecialHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	OpenTime      string                 `protobuf:"bytes,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string                 `protobuf:"bytes,4,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	IsClosed      bool                   `protobuf:"varint,5,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpecialHoursRequest) Reset() {
	*x = SetSpecialHoursRequest{}
	mi := &file_venue_schedule_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpecialHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpecialHoursRequest) ProtoMessage() {}

func (x *SetSpecialHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_schedule_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpecialHoursRequest.ProtoReflect.Descriptor instead.
func (*SetSpecialHoursRequest) Descriptor() ([]byte, []int) {
	return file_venue_schedule_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SetSpecialHoursRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *SetSpecialHoursRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SetSpecialHoursRequest) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *SetSpecialHoursRequest) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

func (x *SetSpecialHoursRequest) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

// Ответы для работы с расписанием
type SetOpeningHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOpeningHoursResponse) Reset() {
	*x = SetOpeningHoursResponse{}
	mi := &file_venue_schedule_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOpeningHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOpeningHoursResponse) ProtoMessage() {}

func (x *SetOpeningHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_schedule_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOpeningHoursResponse.ProtoReflect.Descriptor instead.
func (*SetOpeningHoursResponse) Descriptor() ([]byte, []int) {
	return file_venue_schedule_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SetOpeningHoursResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetSpecialHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpecialHoursResponse) Reset() {
	*x = SetSpecialHoursResponse{}
	mi := &file_venue_schedule_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpecialHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpecialHoursResponse) ProtoMessage() {}

func (x *SetSpecialHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_schedule_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpecialHoursResponse.ProtoReflect.Descriptor instead.
func (*SetSpecialHoursResponse) Descriptor() ([]byte, []int) {
	return file_venue_schedule_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SetSpecialHoursResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_venue_schedule_messages_proto protoreflect.FileDescriptor

const file_venue_schedule_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dvenue/schedule_messages.proto\x12\x05venue\"N\n" +
	"\fOpeningHours\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12#\n" +
	"\x04days\x18\x02 \x03(\v2\x0f.venue.DayHoursR\x04days\"`\n" +
	"\bDayHours\x12\x18\n" +
	"\aweekday\x18\x01 \x01(\x05R\aweekday\x12\x1b\n" +
	"\topen_time\x18\x02 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x03 \x01(\tR\tcloseTime\"\x96\x01\n" +
	"\fSpecialHours\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\topen_time\x18\x03 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x04 \x01(\tR\tcloseTime\x12\x1b\n" +
	"\tis_closed\x18\x05 \x01(\bR\bisClosed\"X\n" +
	"\x16SetOpeningHoursRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12#\n" +
	"\x04days\x18\x02 \x03(\v2\x0f.venue.DayHoursR\x04days\"3\n" +
	"\x16GetOpeningHoursRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\"\xa0\x01\n" +
	"\x16SetSpecialHoursRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\topen_time\x18\x03 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x04 \x01(\tR\tcloseTime\x12\x1b\n" +
	"\tis_closed\x18\x05 \x01(\bR\bisClosed\"3\n" +
	"\x17SetOpeningHoursResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x17SetSpecialHoursResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB5Z3github.com/bookingcontrol/booker-contracts-go/venueb\x06proto3"

var (
	file_venue_schedule_messages_proto_rawDescOnce sync.Once
	file_venue_schedule_messages_proto_rawDescData []byte
)

func file_venue_schedule_messages_proto_rawDescGZIP() []byte {
	file_venue_schedule_messages_proto_rawDescOnce.Do(func() {
		file_venue_schedule_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_venue_schedule_messages_proto_rawDesc), len(file_venue_schedule_messages_proto_rawDesc)))
	})
	return file_venue_schedule_messages_proto_rawDescData
}

var file_venue_schedule_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_venue_schedule_messages_proto_goTypes = []any{
	(*OpeningHours)(nil),            // 0: venue.OpeningHours
	(*DayHours)(nil),                // 1: venue.DayHours
	(*SpecialHours)(nil),            // 2: venue.SpecialHours
	(*SetOpeningHoursRequest)(nil),  // 3: venue.SetOpeningHoursRequest
	(*GetOpeningHoursRequest)(nil),  // 4: venue.GetOpeningHoursRequest
	(*SetSpecialHoursRequest)(nil),  // 5: venue.SetSpecialHoursRequest
	(*SetOpeningHoursResponse)(nil), // 6: venue.SetOpeningHoursResponse
	(*SetSpecialHoursResponse)(nil), // 7: venue.SetSpecialHoursResponse
}
var file_venue_schedule_messages_proto_depIdxs = []int32{
	1, // 0: venue.OpeningHours.days:type_name -> venue.DayHours
	1, // 1: venue.SetOpeningHoursRequest.days:type_name -> venue.DayHours
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_venue_schedule_messages_proto_init() }
func file_venue_schedule_messages_proto_init() {
	if File_venue_schedule_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_venue_schedule_messages_proto_rawDesc), len(file_venue_schedule_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_venue_schedule_messages_proto_goTypes,
		DependencyIndexes: file_venue_schedule_messages_proto_depIdxs,
		MessageInfos:      file_venue_schedule_messages_proto_msgTypes,
	}.Build()
	File_venue_schedule_messages_proto = out.File
	file_venue_schedule_messages_proto_goTypes = nil
	file_venue_schedule_messages_proto_depIdxs = nil
}
