// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: venue/service.proto

package venue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_venue_service_proto protoreflect.FileDescriptor

const file_venue_service_proto_rawDesc = "" +
	"\n" +
	"\x13venue/service.proto\x12\x05venue\x1a\x1avenue/venue_messages.proto\x1a\x19venue/room_messages.proto\x1a\x1avenue/table_messages.proto\x1a\x1dvenue/schedule_messages.proto\x1a!venue/availability_messages.proto2\x92\n" +
	"\n" +
	"\fVenueService\x126\n" +
	"\vCreateVenue\x12\x19.venue.CreateVenueRequest\x1a\f.venue.Venue\x120\n" +
	"\bGetVenue\x12\x16.venue.GetVenueRequest\x1a\f.venue.Venue\x12A\n" +
	"\n" +
	"ListVenues\x12\x18.venue.ListVenuesRequest\x1a\x19.venue.ListVenuesResponse\x126\n" +
	"\vUpdateVenue\x12\x19.venue.UpdateVenueRequest\x1a\f.venue.Venue\x12D\n" +
	"\vDeleteVenue\x12\x19.venue.DeleteVenueRequest\x1a\x1a.venue.DeleteVenueResponse\x123\n" +
	"\n" +
	"CreateRoom\x12\x18.venue.CreateRoomRequest\x1a\v.venue.Room\x12-\n" +
	"\aGetRoom\x12\x15.venue.GetRoomRequest\x1a\v.venue.Room\x12>\n" +
	"\tListRooms\x12\x17.venue.ListRoomsRequest\x1a\x18.venue.ListRoomsResponse\x123\n" +
	"\n" +
	"UpdateRoom\x12\x18.venue.UpdateRoomRequest\x1a\v.venue.Room\x12A\n" +
	"\n" +
	"DeleteRoom\x12\x18.venue.DeleteRoomRequest\x1a\x19.venue.DeleteRoomResponse\x126\n" +
	"\vCreateTable\x12\x19.venue.CreateTableRequest\x1a\f.venue.Table\x120\n" +
	"\bGetTable\x12\x16.venue.GetTableRequest\x1a\f.venue.Table\x12A\n" +
	"\n" +
	"ListTables\x12\x18.venue.ListTablesRequest\x1a\x19.venue.ListTablesResponse\x126\n" +
	"\vUpdateTable\x12\x19.venue.UpdateTableRequest\x1a\f.venue.Table\x12D\n" +
	"\vDeleteTable\x12\x19.venue.DeleteTableRequest\x1a\x1a.venue.DeleteTableResponse\x12P\n" +
	"\x0fSetOpeningHours\x12\x1d.venue.SetOpeningHoursRequest\x1a\x1e.venue.SetOpeningHoursResponse\x12E\n" +
	"\x0fGetOpeningHours\x12\x1d.venue.GetOpeningHoursRequest\x1a\x13.venue.OpeningHours\x12P\n" +
	"\x0fSetSpecialHours\x12\x1d.venue.SetSpecialHoursRequest\x1a\x1e.venue.SetSpecialHoursResponse\x12V\n" +
	"\x11CheckAvailability\x12\x1f.venue.CheckAvailabilityRequest\x1a .venue.CheckAvailabilityResponse\x12M\n" +
	"\x0eGetTableLayout\x12\x1c.venue.GetTableLayoutRequest\x1a\x1d.venue.GetTableLayoutResponseB8Z6github.com/bookingcontrol/booker-contracts-go/v1/venueb\x06proto3"

var file_venue_service_proto_goTypes = []any{
	(*CreateVenueRequest)(nil),        // 0: venue.CreateVenueRequest
	(*GetVenueRequest)(nil),           // 1: venue.GetVenueRequest
	(*ListVenuesRequest)(nil),         // 2: venue.ListVenuesRequest
	(*UpdateVenueRequest)(nil),        // 3: venue.UpdateVenueRequest
	(*DeleteVenueRequest)(nil),        // 4: venue.DeleteVenueRequest
	(*CreateRoomRequest)(nil),         // 5: venue.CreateRoomRequest
	(*GetRoomRequest)(nil),            // 6: venue.GetRoomRequest
	(*ListRoomsRequest)(nil),          // 7: venue.ListRoomsRequest
	(*UpdateRoomRequest)(nil),         // 8: venue.UpdateRoomRequest
	(*DeleteRoomRequest)(nil),         // 9: venue.DeleteRoomRequest
	(*CreateTableRequest)(nil),        // 10: venue.CreateTableRequest
	(*GetTableRequest)(nil),           // 11: venue.GetTableRequest
	(*ListTablesRequest)(nil),         // 12: venue.ListTablesRequest
	(*UpdateTableRequest)(nil),        // 13: venue.UpdateTableRequest
	(*DeleteTableRequest)(nil),        // 14: venue.DeleteTableRequest
	(*SetOpeningHoursRequest)(nil),    // 15: venue.SetOpeningHoursRequest
	(*GetOpeningHoursRequest)(nil),    // 16: venue.GetOpeningHoursRequest
	(*SetSpecialHoursRequest)(nil),    // 17: venue.SetSpecialHoursRequest
	(*CheckAvailabilityRequest)(nil),  // 18: venue.CheckAvailabilityRequest
	(*GetTableLayoutRequest)(nil),     // 19: venue.GetTableLayoutRequest
	(*Venue)(nil),                     // 20: venue.Venue
	(*ListVenuesResponse)(nil),        // 21: venue.ListVenuesResponse
	(*DeleteVenueResponse)(nil),       // 22: venue.DeleteVenueResponse
	(*Room)(nil),                      // 23: venue.Room
	(*ListRoomsResponse)(nil),         // 24: venue.ListRoomsResponse
	(*DeleteRoomResponse)(nil),        // 25: venue.DeleteRoomResponse
	(*Table)(nil),                     // 26: venue.Table
	(*ListTablesResponse)(nil),        // 27: venue.ListTablesResponse
	(*DeleteTableResponse)(nil),       // 28: venue.DeleteTableResponse
	(*SetOpeningHoursResponse)(nil),   // 29: venue.SetOpeningHoursResponse
	(*OpeningHours)(nil),              // 30: venue.OpeningHours
	(*SetSpecialHoursResponse)(nil),   // 31: venue.SetSpecialHoursResponse
	(*CheckAvailabilityResponse)(nil), // 32: venue.CheckAvailabilityResponse
	(*GetTableLayoutResponse)(nil),    // 33: venue.GetTableLayoutResponse
}
var file_venue_service_proto_depIdxs = []int32{
	0,  // 0: venue.VenueService.CreateVenue:input_type -> venue.CreateVenueRequest
	1,  // 1: venue.VenueService.GetVenue:input_type -> venue.GetVenueRequest
	2,  // 2: venue.VenueService.ListVenues:input_type -> venue.ListVenuesRequest
	3,  // 3: venue.VenueService.UpdateVenue:input_type -> venue.UpdateVenueRequest
	4,  // 4: venue.VenueService.DeleteVenue:input_type -> venue.DeleteVenueRequest
	5,  // 5: venue.VenueService.CreateRoom:input_type -> venue.CreateRoomRequest
	6,  // 6: venue.VenueService.GetRoom:input_type -> venue.GetRoomRequest
	7,  // 7: venue.VenueService.ListRooms:input_type -> venue.ListRoomsRequest
	8,  // 8: venue.VenueService.UpdateRoom:input_type -> venue.UpdateRoomRequest
	9,  // 9: venue.VenueService.DeleteRoom:input_type -> venue.DeleteRoomRequest
	10, // 10: venue.VenueService.CreateTable:input_type -> venue.CreateTableRequest
	11, // 11: venue.VenueService.GetTable:input_type -> venue.GetTableRequest
	12, // 12: venue.VenueService.ListTables:input_type -> venue.ListTablesRequest
	13, // 13: venue.VenueService.UpdateTable:input_type -> venue.UpdateTableRequest
	14, // 14: venue.VenueService.DeleteTable:input_type -> venue.DeleteTableRequest
	15, // 15: venue.VenueService.SetOpeningHours:input_type -> venue.SetOpeningHoursRequest
	16, // 16: venue.VenueService.GetOpeningHours:input_type -> venue.GetOpeningHoursRequest
	17, // 17: venue.VenueService.SetSpecialHours:input_type -> venue.SetSpecialHoursRequest
	18, // 18: venue.VenueService.CheckAvailability:input_type -> venue.CheckAvailabilityRequest
	19, // 19: venue.VenueService.GetTableLayout:input_type -> venue.GetTableLayoutRequest
	20, // 20: venue.VenueService.CreateVenue:output_type -> venue.Venue
	20, // 21: venue.VenueService.GetVenue:output_type -> venue.Venue
	21, // 22: venue.VenueService.ListVenues:output_type -> venue.ListVenuesResponse
	20, // 23: venue.VenueService.UpdateVenue:output_type -> venue.Venue
	22, // 24: venue.VenueService.DeleteVenue:output_type -> venue.DeleteVenueResponse
	23, // 25: venue.VenueService.CreateRoom:output_type -> venue.Room
	23, // 26: venue.VenueService.GetRoom:output_type -> venue.Room
	24, // 27: venue.VenueService.ListRooms:output_type -> venue.ListRoomsResponse
	23, // 28: venue.VenueService.UpdateRoom:output_type -> venue.Room
	25, // 29: venue.VenueService.DeleteRoom:output_type -> venue.DeleteRoomResponse
	26, // 30: venue.VenueService.CreateTable:output_type -> venue.Table
	26, // 31: venue.VenueService.GetTable:output_type -> venue.Table
	27, // 32: venue.VenueService.ListTables:output_type -> venue.ListTablesResponse
	26, // 33: venue.VenueService.UpdateTable:output_type -> venue.Table
	28, // 34: venue.VenueService.DeleteTable:output_type -> venue.DeleteTableResponse
	29, // 35: venue.VenueService.SetOpeningHours:output_type -> venue.SetOpeningHoursResponse
	30, // 36: venue.VenueService.GetOpeningHours:output_type -> venue.OpeningHours
	31, // 37: venue.VenueService.SetSpecialHours:output_type -> venue.SetSpecialHoursResponse
	32, // 38: venue.VenueService.CheckAvailability:output_type -> venue.CheckAvailabilityResponse
	33, // 39: venue.VenueService.GetTableLayout:output_type -> venue.GetTableLayoutResponse
	20, // [20:40] is the sub-list for method output_type
	0,  // [0:20] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_venue_service_proto_init() }
func file_venue_service_proto_init() {
	if File_venue_service_proto != nil {
		return
	}
	file_venue_venue_messages_proto_init()
	file_venue_room_messages_proto_init()
	file_venue_table_messages_proto_init()
	file_venue_schedule_messages_proto_init()
	file_venue_availability_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_venue_service_proto_rawDesc), len(file_venue_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_venue_service_proto_goTypes,
		DependencyIndexes: file_venue_service_proto_depIdxs,
	}.Build()
	File_venue_service_proto = out.File
	file_venue_service_proto_goTypes = nil
	file_venue_service_proto_depIdxs = nil
}
