// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: venue/venue_messages.proto

package venue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сущность заведения
type Venue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Venue) Reset() {
	*x = Venue{}
	mi := &file_venue_venue_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Venue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Venue) ProtoMessage() {}

func (x *Venue) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Venue.ProtoReflect.Descriptor instead.
func (*Venue) Descriptor() ([]byte, []int) {
	return file_venue_venue_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Venue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Venue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Venue) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Venue) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Venue) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Venue) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Запросы для работы с заведениями
type CreateVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVenueRequest) Reset() {
	*x = CreateVenueRequest{}
	mi := &file_venue_venue_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVenueRequest) ProtoMessage() {}

func (x *CreateVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVenueRequest.ProtoReflect.Descriptor instead.
func (*CreateVenueRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVenueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVenueRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateVenueRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVenueRequest) Reset() {
	*x = GetVenueRequest{}
	mi := &file_venue_venue_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVenueRequest) ProtoMessage() {}

func (x *GetVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVenueRequest.ProtoReflect.Descriptor instead.
func (*GetVenueRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetVenueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListVenuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVenuesRequest) Reset() {
	*x = ListVenuesRequest{}
	mi := &file_venue_venue_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVenuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVenuesRequest) ProtoMessage() {}

func (x *ListVenuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVenuesRequest.ProtoReflect.Descriptor instead.
func (*ListVenuesRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ListVenuesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVenuesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVenueRequest) Reset() {
	*x = UpdateVenueRequest{}
	mi := &file_venue_venue_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVenueRequest) ProtoMessage() {}

func (x *UpdateVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVenueRequest.ProtoReflect.Descriptor instead.
func (*UpdateVenueRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateVenueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVenueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateVenueRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeleteVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVenueRequest) Reset() {
	*x = DeleteVenueRequest{}
	mi := &file_venue_venue_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVenueRequest) ProtoMessage() {}

func (x *DeleteVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVenueRequest.ProtoReflect.Descriptor instead.
func (*DeleteVenueRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteVenueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответы для работы с заведениями
type ListVenuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Venues        []*Venue               `protobuf:"bytes,1,rep,name=venues,proto3" json:"venues,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVenuesResponse) Reset() {
	*x = ListVenuesResponse{}
	mi := &file_venue_venue_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVenuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVenuesResponse) ProtoMessage() {}

func (x *ListVenuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVenuesResponse.ProtoReflect.Descriptor instead.
func (*ListVenuesResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ListVenuesResponse) GetVenues() []*Venue {
	if x != nil {
		return x.Venues
	}
	return nil
}

func (x *ListVenuesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteVenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVenueResponse) Reset() {
	*x = DeleteVenueResponse{}
	mi := &file_venue_venue_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVenueResponse) ProtoMessage() {}

func (x *DeleteVenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVenueResponse.ProtoReflect.Descriptor instead.
func (*DeleteVenueResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVenueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_venue_venue_messages_proto protoreflect.FileDescriptor

const file_venue_venue_messages_proto_rawDesc = "" +
	"\n" +
	"\x1avenue/venue_messages.proto\x12\x05venue\"\x9f\x01\n" +
	"\x05Venue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"^\n" +
	"\x12CreateVenueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"!\n" +
	"\x0fGetVenueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x11ListVenuesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"R\n" +
	"\x12UpdateVenueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"$\n" +
	"\x12DeleteVenueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x12ListVenuesResponse\x12$\n" +
	"\x06venues\x18\x01 \x03(\v2\f.venue.VenueR\x06venues\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"/\n" +
	"\x13DeleteVenueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB5Z3github.com/bookingcontrol/booker-contracts-go/venueb\x06proto3"

var (
	file_venue_venue_messages_proto_rawDescOnce sync.Once
	file_venue_venue_messages_proto_rawDescData []byte
)

func file_venue_venue_messages_proto_rawDescGZIP() []byte {
	file_venue_venue_messages_proto_rawDescOnce.Do(func() {
		file_venue_venue_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_venue_venue_messages_proto_rawDesc), len(file_venue_venue_messages_proto_rawDesc)))
	})
	return file_venue_venue_messages_proto_rawDescData
}

var file_venue_venue_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_venue_venue_messages_proto_goTypes = []any{
	(*Venue)(nil),               // 0: venue.Venue
	(*CreateVenueRequest)(nil),  // 1: venue.CreateVenueRequest
	(*GetVenueRequest)(nil),     // 2: venue.GetVenueRequest
	(*ListVenuesRequest)(nil),   // 3: venue.ListVenuesRequest
	(*UpdateVenueRequest)(nil),  // 4: venue.UpdateVenueRequest
	(*DeleteVenueRequest)(nil),  // 5: venue.DeleteVenueRequest
	(*ListVenuesResponse)(nil),  // 6: venue.ListVenuesResponse
	(*DeleteVenueResponse)(nil), // 7: venue.DeleteVenueResponse
}
var file_venue_venue_messages_proto_depIdxs = []int32{
	0, // 0: venue.ListVenuesResponse.venues:type_name -> venue.Venue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_venue_venue_messages_proto_init() }
func file_venue_venue_messages_proto_init() {
	if File_venue_venue_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_venue_venue_messages_proto_rawDesc), len(file_venue_venue_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_venue_venue_messages_proto_goTypes,
		DependencyIndexes: file_venue_venue_messages_proto_depIdxs,
		MessageInfos:      file_venue_venue_messages_proto_msgTypes,
	}.Build()
	File_venue_venue_messages_proto = out.File
	file_venue_venue_messages_proto_goTypes = nil
	file_venue_venue_messages_proto_depIdxs = nil
}
